Simplified travel times
pioneerspacesim/pioneer pull request #5707
Opened 2024-01-06 16:25 UTC by robothauler

This is an attempt to simplify delivery times so that they can be better balanced if necessary.

I have used the DeliverPackage module as a basis and fitted the other with one factor.
![deliverpackage](https://github.com/pioneerspacesim/pioneer/assets/10255455/05470b36-05b1-4e22-84e6-9d19ca4e6f01)
![cargorun](https://github.com/pioneerspacesim/pioneer/assets/10255455/d0562054-41df-4029-9c10-06eafb6ad9c0)
![taxi](https://github.com/pioneerspacesim/pioneer/assets/10255455/ddad5d61-fc98-488e-b297-91b074ccbd7b)
![assassination](https://github.com/pioneerspacesim/pioneer/assets/10255455/b031afcd-178f-4722-9413-dce22c581aeb)

The combat module is now better for ships like the Bowfin.
![combat](https://github.com/pioneerspacesim/pioneer/assets/10255455/304d35ca-1c01-4b0e-9424-4ab2d868c38d)

I have also added a "local part". This should calculate much better delivery times for large systems.
If no location is specified, a distance of 1AU is assumed.

**Now the local deliveries:**

I took the average flight time of a Xylophis from 'System Administration Resting' to 'OPLI Pax' as the basis for the local deliveries. approx. 2 days for 1AU.
![local](https://github.com/pioneerspacesim/pioneer/assets/10255455/63e8f728-a238-4fa8-a637-4be3f35bb38b)
![scoop](https://github.com/pioneerspacesim/pioneer/assets/10255455/5d0e12fa-f879-4aaf-817c-e50bc958b89d)

Finally, the due time is rounded to 1h or 1/4h. In addition, the advert is deleted after half of the calculated travel time. Makes more sense in my opinion.

2024-01-07 17:51 UTC, Web-eWorks requested changes
Please define the `travelTimeLocal` and `travelTime` functions in `data/modules/MissionUtils.lua` instead.

We already have some helpers for calculating mission parameters in that file, and the top-level `utils.lua` file is intended for general-purpose "language level" utilities.

Otherwise, I'm quite happy to see some effort be made to standardize balance across multiple mission modules and provide more tools to adjust and tweak the balance of the whole game "in one place"!

If you are willing to make additional changes, I'd like to see the mission duration and reward calculations used by each module unified into a common function (or set of functions) operating on some set of semantically well-defined variables similar to the current MissionUtils.Calculator helper.

2024-01-09 08:16 UTC, impaktor commented
Welcomed indeed. My gut feeling tells me this needs a bit of play testing to find edge cases, and might be better suitable for merge after pioneer-day, so only people building from source will be play-testing it, to find if there's some mission time limit that's unfair / doesn't make sense.

2024-01-12 01:17 UTC, Web-eWorks commented on data/modules/Assassination/Assassination.lua
> +local MissionUtils = require "modules.MissionUtils"
As a matter of convention, we prefer to use single-quotes for module names, especially when omitting the parentheses to `require()`.

2024-01-12 01:22 UTC, Web-eWorks commented on data/modules/MissionUtils.lua
> +function MissionUtils.travelTimeLocal(distance)
By convention, we use `PascalCase` for functions defined in a class or namespace like this, with the general idea that a leading capital letter in the module name requires a leading capital letter in the function name. `camelCase` names should be reserved for instance or class variables.

`utils` is a bit of a special case in that it's written in "Lua stdlib style" as it's meant to be a semi-portable extension to the Lua utility functions that isn't directly dependent on any game-specific code.

2024-01-12 01:27 UTC, Web-eWorks approved these changes
Looks good to me! I've left a few comments where the formatting of the code isn't uniform with our existing style conventions, but otherwise the code is approved.

Regarding balance, I've not yet played with it but the graphs look sensible. I'll make an effort to playtest this at some point, but I believe we can issue a post-Pioneer-day release if the balance is significantly negatively affected in a way that we don't catch.

2024-01-14 01:50 UTC, merged