improve planet rings shaders
pioneerspacesim/pioneer pull request #5708
Opened 2024-01-08 11:20 UTC by Mc-Pain

All rings are assumed to be icy

1) Each object in ring is darker depending of its phase
   (like Moon phases)
2) Each object shines brightly if sun is behind the ring
   (lot of low angle specular reflections)
3) Each object shines brightly if looking from the sun
   (simulating high geometric albedo > 1.0)

2024-01-09 01:50 UTC, Web-eWorks commented
![Snapshot_2024-01-08_20-44-24](https://github.com/pioneerspacesim/pioneer/assets/4218491/5e4a0d05-82ca-4792-92a0-59b69bd3e60d)
![Snapshot_2024-01-08_20-42-59](https://github.com/pioneerspacesim/pioneer/assets/4218491/fe764e9f-8682-4606-a6a3-e629d1660269)
![Snapshot_2024-01-08_20-42-01](https://github.com/pioneerspacesim/pioneer/assets/4218491/855d4a24-71ca-4c94-b7fa-662087d0647b)
![Snapshot_2024-01-08_20-40-12](https://github.com/pioneerspacesim/pioneer/assets/4218491/241b2741-7e0d-4089-b3c6-541cf9942a51)

This looks *quite* good, excellent work! I have two concerns:
- First, there is a clear black "terminator" at the inner and outer edges of the overall ring structures. I assume this is probably caused by erroneous vertex colors being passed when generating the ring meshes. I'd like to see this resolved before merge.
- Secondly, there's a clear/sharp shadow terminator between shadowed portions of the ring and unshadowed portions. I'd like to see a softer shadow computation here, as the current terminator is not only a bit unnatural (ignores partially-shadowed light reaching the ring / gravitational lensing / edge-of-atmosphere light diffusion) but also suffers from a lack of anti-aliasing.
  This is not a concern that needs to be addressed before merge, but I would like to be improved post-merge if you are able.

2024-01-09 02:21 UTC, Web-eWorks requested changes

2024-01-09 02:21 UTC, Web-eWorks commented on data/shaders/opengl/planetrings.frag
> +			float phaseReflect = 3.f / (8.f * 3.141592) * ((1.f - g * g) * (1.f + muRev * muRev)) / ((2.f + g * g) * pow(1.f + g * g - 2.f * g * muRev, 1.5f));
I'd prefer `phaseReflect` and `phaseThrough` equations be consolidated to a single function parameterized on `mu` / `muRev`, with a comment indicating the equation's source and ideally with a link to the article or resource the Mie phase equation is derived from.

2024-01-09 07:59 UTC, impaktor commented
> Secondly, there's a clear/sharp shadow terminator between shadowed portions of the ring and unshadowed portions. I'd like to see a softer shadow computation here .... This is not a concern that needs to be addressed before merge

Indeed, this can be left to another day. But forgive me if I sound like an imbecile, but shadows in vacuum of space are very "hard", right?. So personally, I don't see that as an issue, (but I haven't tried the branch).

2024-01-09 08:41 UTC, nozmajner commented
@impaktor Shadows softness is more of a fiction of the size of the light source and the distance between the object and the surface where the shadow is cast. The bigger it is, the softer the shadows, and the further away the surface is, the softer as well. You can observ this even here on Earth: the shadow of a tall pole will be much sharper at the base compared to its top/furthest from the object. Similar to how they show the penumbra on those lunar eclipse explanations: 
![Geometry_of_a_Lunar_Eclipse svg](https://github.com/pioneerspacesim/pioneer/assets/4182678/3a10e07e-8937-49c3-acef-794eb9ebddfe)


The Sun is about 10 times larger than Saturn for example, and the shadow on the rings would look about like this: 
![image](https://github.com/pioneerspacesim/pioneer/assets/4182678/b00b9115-7358-45d0-839e-689a6c5e35a1)
(Quickly put together in Blender, Saturn and Sun size and distance is to scale)

2024-01-10 03:06 UTC, Web-eWorks commented
Additionally, the sharpness of the shadow is partially because the shadowing condition is evaluated per screen pixel and produces a very "jagged" edge without any attempt at anti-aliasing.

2024-01-17 10:58 UTC, Web-eWorks approved these changes

2024-01-18 05:31 UTC, merged